name: Docker Build and Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: windows-latest
    env:
      DOCKER_USERNAME: doubledaan
      DOCKER_PASSWORD: bU0C6kozN0lAW4k8WIlalP406p
    steps:
      # - name: 运行时间
      #   run: |
      #     export TZ='Asia/Shanghai'
      #     echo "当前时间: $(date '+%Y-%m-%d %H:%M:%S')"
      #     echo "当前时间戳: $(date +%s)"

      - name: 检出代码
        uses: actions/checkout@v4

      - name: 登录到Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: 运行容器
        shell: cmd
        run: |
          curl ipinfo.io

          

          # echo "mynewpassword" | passwd --stdin

          echo "runner:mynewpassword" | sudo chpasswd

          docker run -d -p 1234:1234 --restart=always alpine/socat TCP-LISTEN:1234,fork TCP:172.17.0.1:3389

          curl -L "https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          
          echo "Run ID: ${{ github.run_id }}"
          sed -i -e 's/USER/${{ github.actor }}/' ./frpc.toml
          # cat ./frpc.toml
          docker run \
          --name frpc \
          -v ./frpc.toml:/etc/frp/frpc.toml \
          --add-host host.docker.internal:172.17.0.1 \
          snowdreamtech/frpc
          # docker run -d -p 8388:1234 --restart=always alpine/socat TCP-LISTEN:1234,fork TCP:8.217.1.158:8388
          
          # cd gamecenter
          # docker-compose up -d mongo
          # sleep 5
          # docker-compose up -d app
          # docker-compose logs -f app

      # - name: 保存数据库
      #   if: always()  # 确保无论成功或失败都运行
      #   run: |
      #     cd gamecenter
      #     ls
      #     echo "当前时间: $(date '+%Y-%m-%d %H:%M:%S')"
      #     echo "当前时间戳: $(date +%s)"
      #     docker stop frpc
      #     docker commit gamecenter-mongo-1 ${{ env.DOCKER_USERNAME }}/mongo
      #     docker push ${{ env.DOCKER_USERNAME }}/mongo
